import type { ModuleEnhancement } from '@/types/course';

export const aiProgrammingEnhancement: ModuleEnhancement = {
  lastVerifiedOn: '2026-04-03',
  sources: [
    { label: 'Claude Code Overview', url: 'https://code.claude.com/docs/en/overview' },
    { label: 'OpenAI Codex', url: 'https://developers.openai.com/codex' },
    { label: 'OpenAI Codex CLI', url: 'https://developers.openai.com/codex/cli' },
    { label: 'Gemini CLI GitHub', url: 'https://github.com/google-gemini/gemini-cli' },
    { label: 'Gemini Code Assist', url: 'https://developers.google.com/gemini-code-assist' },
    { label: 'Google Antigravity', url: 'https://developers.googleblog.com/en/build-with-google-antigravity-our-new-agentic-development-platform/' },
    { label: 'Cursor Docs', url: 'https://docs.cursor.com/' },
    { label: 'Cursor Background Agents', url: 'https://docs.cursor.com/background-agent/overview' },
    { label: 'Kiro Docs', url: 'https://kiro.dev/docs/' },
    { label: 'Lingma Docs', url: 'https://help.aliyun.com/zh/lingma/' },
    { label: 'Qoder Docs', url: 'https://docs.qoder.com/zh/' },
    { label: 'Qwen3-Coder GitHub', url: 'https://github.com/QwenLM/Qwen3-Coder' },
    { label: 'TRAE China', url: 'https://www.trae.cn/' },
    { label: 'MarsCode', url: 'https://www.marscode.com/' },
    { label: 'CodeBuddy Docs', url: 'https://copilot.tencent.com/docs/ide/Introduction' },
    { label: 'CodeBuddy CLI', url: 'https://copilot.tencent.com/docs/cli/quickstart' },
    { label: 'IDC China AI Code Generation Report 2024', url: 'https://www.amazonaws.cn/about-aws/analyst-reports/2024-idc-china-ai-code-generation-technology-assessment-report/' },
    { label: 'DeepSeek Pricing', url: 'https://api-docs.deepseek.com/quick_start/pricing/' },
    { label: 'GLM Pricing', url: 'https://docs.z.ai/guides/overview/pricing' },
    { label: 'GLM-5 Docs', url: 'https://docs.z.ai/guides/llm/glm-5' },
    { label: 'Kimi Platform', url: 'https://platform.moonshot.cn/' },
    { label: 'MiniMax Platform', url: 'https://platform.minimax.io/' },
    { label: 'MiniMax Pricing', url: 'https://platform.minimax.io/docs/guides/pricing-paygo' },
    { label: 'Doubao Pricing', url: 'https://www.volcengine.com/docs/84458/1585097' },
    { label: 'Qwen Pricing', url: 'https://help.aliyun.com/document_detail/2840914.html' },
    { label: 'OpenAI Pricing', url: 'https://openai.com/api/pricing/' },
    { label: 'Anthropic Pricing', url: 'https://www.anthropic.com/pricing#api' },
    { label: 'Gemini Pricing', url: 'https://ai.google.dev/gemini-api/docs/pricing' },
  ],
  blocks: [
    {
      type: 'tool-comparison',
      title: '国际前沿工具 vs 国内落地工具',
      description: '这不是优劣榜，而是两条产品路线的典型差异。选型时先看你的团队约束，再看工具上限。',
      cliTitle: '国际前沿工具',
      coworkTitle: '国内落地工具',
      items: [
        {
          aspect: '典型代表',
          cli: 'Claude Code、Codex、Cursor、Gemini CLI / Antigravity、Kiro。',
          cowork: '通义灵码、Qoder、TRAE、CodeBuddy，以及围绕 Qwen、豆包、DeepSeek 等模型构建的企业落地栈。',
        },
        {
          aspect: '默认入口',
          cli: '终端、IDE、云端任务台并存，强调代理执行和多入口协同。',
          cowork: 'IDE 插件、企业控制台、中文化产品界面，强调易接入和团队推广。',
        },
        {
          aspect: '最强项',
          cli: '产品创新快，工作流范式领先，Agent、异步任务、规则系统更新频繁。',
          cowork: '中文体验、采购和支付便利、企业生态协同、私有化或云厂商接入更顺。',
        },
        {
          aspect: '上下文与规则',
          cli: '项目级指令文件、Rules、Hooks、Specs、Background Agents 等形态更丰富。',
          cowork: '更强调企业知识库、项目配置、组织级治理和团队统一规范。',
        },
        {
          aspect: '适合谁',
          cli: '追求能力上限、愿意折腾新工作流的开发者和技术团队。',
          cowork: '需要大规模推广、重视中文体验和内网/合规接入的中国团队。',
        },
        {
          aspect: '最大注意点',
          cli: '学习门槛更高，部分产品依赖海外账号、支付、网络或云端执行。',
          cowork: '前沿能力节奏可能略慢于海外，强依赖各家生态与采购路径。',
        },
      ],
    },
    {
      type: 'security-checklist',
      title: 'AI 编程最小治理清单',
      description: '真正可持续的 AI 编程，不靠“模型懂事”，靠把危险动作、敏感数据和回退点写成规则。',
      items: [
        {
          title: '先划清本地执行与云端执行',
          detail: '本地执行适合高敏感仓库和强监督流程；云端执行适合可并行、可委托的低到中风险任务。不要混着用却不区分数据边界。',
        },
        {
          title: 'Secrets 默认不可见',
          detail: '密钥、生产配置、证书、客户数据和内网凭证默认隔离，只有经过明确批准的任务才允许访问。',
        },
        {
          title: '危险操作必须有人确认',
          detail: '删除文件、安装依赖、推远端分支、改 CI/CD、发外部请求、写数据库都应该有确认点。',
        },
        {
          title: '所有主流程都要有回退路径',
          detail: '至少保留 git 备份、变更 diff、自检步骤和人工兜底。没有回退，就不要开放高权限自动化。',
        },
        {
          title: '成本看总拥有成本',
          detail: '不要只看单次 token 单价，还要把返工、等待、人工审核和云端并行失败重跑一并计算。',
        },
        {
          title: '团队必须留审计痕迹',
          detail: '谁发起了什么任务、改了哪些文件、是否跑过验证、谁批准了高风险动作，都应该能追溯。',
        },
      ],
    },
    {
      type: 'weekly-plan',
      title: '4 周落地路线：从工具试用到稳定流程',
      description: '不要一上来铺满全团队。先跑通一条真实流程，再逐步扩到模型分工、治理和团队协作。',
      items: [
        {
          week: 1,
          goal: '选默认入口',
          deliverable: '分别试 1 个 CLI Agent、1 个 IDE Agent、1 个国内工具，写出你的主入口与备选入口。',
          fallback: '如果判断不清，就拿同一个真实小任务分别试 20 分钟，用返工量和等待成本做决定。',
        },
        {
          week: 2,
          goal: '建模型角色表',
          deliverable: '为复杂任务、日常任务、批量任务各指定 1 个默认模型和 1 个回退模型。',
          fallback: '如果数据不够，就先从 3 类高频任务开始，不要一口气覆盖全部场景。',
        },
        {
          week: 3,
          goal: '跑通一条标准工作流',
          deliverable: '把 1 条需求到 PR 的流程写成 SOP，至少包含读、计划、执行、验证、总结五步。',
          fallback: '如果多人协作太复杂，就先在个人仓库里完成一条简化版流程。',
        },
        {
          week: 4,
          goal: '补齐治理边界',
          deliverable: '完成权限规则、Secrets 策略、审计记录和回退方案，形成团队试运行版规范。',
          fallback: '如果还不敢团队推广，就先限定在单仓库、单团队、低风险任务试运行。',
        },
      ],
    },
    {
      type: 'resource-links',
      title: '官方资源导航',
      description: '后续课程正文落地和版本维护，优先回到这些官方入口核验，不用先看社区二手结论。',
      items: [
        {
          title: 'Claude Code Overview',
          url: 'https://code.claude.com/docs/en/overview',
          label: 'Anthropic',
          description: 'Claude Code 核心能力、入口与工作方式',
          category: '国外工具',
        },
        {
          title: 'OpenAI Codex',
          url: 'https://developers.openai.com/codex',
          label: 'OpenAI',
          description: 'Codex 产品总览与云端代理工作方式',
          category: '国外工具',
        },
        {
          title: 'OpenAI Codex CLI',
          url: 'https://developers.openai.com/codex/cli',
          label: 'OpenAI',
          description: 'Codex CLI 安装、模型和命令行工作流',
          category: '国外工具',
        },
        {
          title: 'Gemini CLI',
          url: 'https://github.com/google-gemini/gemini-cli',
          label: 'Google',
          description: '开源终端 Agent、工具调用和扩展入口',
          category: '国外工具',
        },
        {
          title: 'Google Antigravity',
          url: 'https://developers.googleblog.com/en/build-with-google-antigravity-our-new-agentic-development-platform/',
          label: 'Google',
          description: 'Google 的 agent 开发平台，强调编辑器、终端、浏览器与多 Agent 协同',
          category: '国外工具',
        },
        {
          title: 'Cursor Background Agents',
          url: 'https://docs.cursor.com/background-agent/overview',
          label: 'Cursor',
          description: 'Cursor 的异步代理工作方式与适用场景',
          category: '国外工具',
        },
        {
          title: 'Kiro Docs',
          url: 'https://kiro.dev/docs/',
          label: 'Kiro',
          description: 'Specs、Steering、Hooks 等核心概念',
          category: '国外工具',
        },
        {
          title: 'Anthropic API Pricing',
          url: 'https://www.anthropic.com/pricing#api',
          label: 'Anthropic',
          description: 'Claude 系列模型的官方 API 价格页',
          category: '国外模型',
        },
        {
          title: 'OpenAI API Pricing',
          url: 'https://openai.com/api/pricing/',
          label: 'OpenAI',
          description: 'GPT / Codex 系列模型的官方 API 价格页',
          category: '国外模型',
        },
        {
          title: 'Gemini API Pricing',
          url: 'https://ai.google.dev/gemini-api/docs/pricing',
          label: 'Google',
          description: 'Gemini 系列模型的官方 API 价格与免费配额说明',
          category: '国外模型',
        },
        {
          title: '通义灵码官方文档',
          url: 'https://help.aliyun.com/zh/lingma/',
          label: '阿里',
          description: '通义灵码产品能力、接入方式和企业文档',
          category: '国内工具',
        },
        {
          title: 'Qoder 官方文档',
          url: 'https://docs.qoder.com/zh/',
          label: '阿里',
          description: 'Qoder 的 Quest、Repo Wiki、Rules、Hooks 与团队能力',
          category: '国内工具',
        },
        {
          title: 'Qwen3-Coder',
          url: 'https://github.com/QwenLM/Qwen3-Coder',
          label: '阿里',
          description: 'Qwen 编程模型与开源编码路线',
          category: '国内模型',
        },
        {
          title: '阿里云百炼模型与价格',
          url: 'https://help.aliyun.com/document_detail/2840914.html',
          label: '阿里',
          description: 'Qwen 商业模型、上下文分档与最新官方价格',
          category: '国内模型',
        },
        {
          title: 'TRAE 中国版',
          url: 'https://www.trae.cn/',
          label: '字节',
          description: 'TRAE 产品首页和能力入口',
          category: '国内工具',
        },
        {
          title: 'MarsCode',
          url: 'https://www.marscode.com/',
          label: '字节',
          description: '字节系 AI Coding 平台与开发者入口',
          category: '国内工具',
        },
        {
          title: '腾讯云代码助手 CodeBuddy',
          url: 'https://copilot.tencent.com/docs/ide/Introduction',
          label: '腾讯',
          description: 'IDE、CLI 与团队协作能力入口',
          category: '国内工具',
        },
        {
          title: 'GLM 定价',
          url: 'https://docs.z.ai/guides/overview/pricing',
          label: '智谱',
          description: 'GLM 与 GLM-Code 官方价格页',
          category: '国内模型',
        },
        {
          title: 'GLM-5 官方说明',
          url: 'https://docs.z.ai/guides/llm/glm-5',
          label: '智谱',
          description: 'GLM-5 系列能力说明与接入入口',
          category: '国内模型',
        },
        {
          title: 'Kimi 开放平台',
          url: 'https://platform.moonshot.cn/',
          label: '月之暗面',
          description: 'Kimi 模型、控制台与官方接入入口',
          category: '国内模型',
        },
        {
          title: 'MiniMax 开放平台',
          url: 'https://platform.minimax.io/',
          label: 'MiniMax',
          description: 'MiniMax 模型平台与控制台首页',
          category: '国内模型',
        },
        {
          title: 'MiniMax Pay as You Go',
          url: 'https://platform.minimax.io/docs/guides/pricing-paygo',
          label: 'MiniMax',
          description: 'MiniMax 按量计费、套餐与模型价格说明',
          category: '国内模型',
        },
        {
          title: '豆包模型与费用',
          url: 'https://www.volcengine.com/docs/84458/1585097',
          label: '字节',
          description: '豆包模型价格、上下文分档与费用口径',
          category: '国内模型',
        },
        {
          title: 'DeepSeek API Pricing',
          url: 'https://api-docs.deepseek.com/quick_start/pricing/',
          label: 'DeepSeek',
          description: 'DeepSeek 官方 API 定价与缓存价格说明',
          category: '国内模型',
        },
        {
          title: 'IDC 中国 AI 代码生成技术评估报告（摘要页）',
          url: 'https://www.amazonaws.cn/about-aws/analyst-reports/2024-idc-china-ai-code-generation-technology-assessment-report/',
          label: 'IDC',
          description: '行业侧对中国 AI 代码生成产品能力与演进方向的评估摘要',
          category: '行业资料',
        },
      ],
    },
  ],
};
