import type { ModuleEnhancement } from '@/types/course';

export const casesEnhancement: ModuleEnhancement = {
  lastVerifiedOn: '2026-06-08',
  sources: [
    { label: 'OpenClaw Cron 官方文档', url: 'https://docs.openclaw.ai/automation/cron-jobs' },
    { label: 'OpenClaw Heartbeat 官方文档', url: 'https://docs.openclaw.ai/gateway/heartbeat' },
    { label: 'OpenClaw Skills 官方文档', url: 'https://docs.openclaw.ai/tools/skills' },
    { label: '飞书自定义机器人使用指南', url: 'https://open.feishu.cn/document/client-docs/bot-v3/add-custom-bot' },
    { label: '飞书多维表格列出记录 API', url: 'https://open.feishu.cn/document/server-docs/docs/bitable-v1/app-table-record/list' },
    { label: 'Claude Code 官方文档', url: 'https://docs.anthropic.com/en/docs/claude-code/overview' },
    { label: 'Trae 官方文档', url: 'https://docs.trae.ai/' },
    { label: 'GitHub Actions schedule 官方文档', url: 'https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#schedule' },
    { label: 'GitHub Actions 计费官方文档', url: 'https://docs.github.com/en/billing/concepts/product-billing/github-actions' },
    { label: 'GitHub Actions Secrets 官方文档', url: 'https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-secrets' },
    { label: 'Vercel 官方文档', url: 'https://vercel.com/docs' },
    { label: '微信服务号草稿箱官方文档', url: 'https://developers.weixin.qq.com/doc/service/guide/product/draft.html' },
    { label: '微信服务号发布能力官方文档', url: 'https://developers.weixin.qq.com/doc/service/guide/product/publish.html' },
    { label: '微信服务号群发消息官方文档', url: 'https://developers.weixin.qq.com/doc/service/guide/product/message/Batch_Sends.html' },
    { label: '小红书开放平台官网', url: 'https://open.xiaohongshu.com/' },
  ],
  blocks: [
    {
      type: 'action-checklist',
      title: '案例落地前检查',
      description: '每个案例都先过这 5 个问题，避免把“看起来能自动化”误当成“已经适合上线”。',
      hideMeta: true,
      items: [
        {
          title: '适用人群说清楚',
          description: '确认这个案例解决的是你的真实重复工作，而不是别人案例里的热闹场景。',
          timebox: '10 分钟',
          doneDefinition: '能写出使用者、当前工作流、最痛的步骤和为什么现在要改。',
        },
        {
          title: '输入材料准备好',
          description: '把信息源、数据源、文档、账号权限、渠道和人工负责人列成清单。',
          timebox: '15 分钟',
          doneDefinition: '不依赖“到时候再找”，第一版所需材料都能拿到或明确替代方案。',
        },
        {
          title: 'MVP 边界缩到最小',
          description: '第一版只跑通主流程，不默认接支付、不自动外发、不碰高风险生产动作。',
          timebox: '15 分钟',
          doneDefinition: '能用一句话说明第一版做到哪一步就停止扩展。',
        },
        {
          title: '风险边界写进规则',
          description: '把需要人工确认的平台发布、数字核对、权限申请、对外发送和正式部署写成硬规则。',
          timebox: '20 分钟',
          doneDefinition: '高风险动作都有“必须确认”或“以官方当前页面为准”的处理方式。',
        },
        {
          title: '验收结果可观察',
          description: '把“好像有用”改成具体结果：收到消息、生成草稿、脚本跑通、数字核对一致、页面可访问。',
          timebox: '10 分钟',
          doneDefinition: '能手动触发一次，并对照清单判断通过或失败。',
        },
      ],
    },
    {
      type: 'sop-templates',
      title: '6 个案例的最小交付物',
      description: '每个案例只保留第一版真正需要验收的产物，后续扩展等 MVP 稳定后再加。',
      hideMeta: true,
      items: [
        {
          title: '内容矩阵自动化',
          input: '内容垂类、信息源、风格规则、飞书审核群、发布渠道权限说明。',
          steps: ['安装搜索技能', '写内容规则', '创建 Cron 初稿任务', '推送飞书审核', '人工确认发布或修改'],
          output: '一条结构化内容初稿进入飞书审核频道。',
          kpi: '人工能根据“发布/修改/暂缓”完成接力，系统不越过审核直接外发。',
        },
        {
          title: '市场研究与产品机会发现',
          input: '研究范围、公开来源、自有反馈、机会评分卡。',
          steps: ['限定用户和场景', '建立来源池', '写评分卡', '每周汇总', '生成一页问题简报'],
          output: '一页可进入访谈或 MVP 验证的问题简报。',
          kpi: '简报能回答谁在痛、痛在哪里、现有替代方案是什么、下一步验证什么。',
        },
        {
          title: '行业竞品监控日报',
          input: '行业来源、竞品页面、关键词、告警频道和责任人。',
          steps: ['整理监控清单', '安装搜索技能', '写过滤规则', '创建 Cron 日报', '手动触发并调优'],
          output: '飞书收到一条精选行业日报，必要告警单独分流。',
          kpi: '内容相关、来源清楚、条数可控、广告和低相关信息不进告警。',
        },
        {
          title: 'Vibe Coding 产品上线',
          input: '产品描述文档、第一版功能、不做清单、成功标准。',
          steps: ['写产品描述', '让 AI 挑错', '选择工具', '逐功能构建', '部署可访问版本', '收集反馈'],
          output: '一个能访问并完成主流程的验证版产品。',
          kpi: '主流程可跑通，已记录首轮反馈，并能判断下一步是继续、改方向还是停止。',
        },
        {
          title: '个人产品 MVP 推进助手',
          input: '目标卡、项目文件夹、任务边界、飞书通知入口。',
          steps: ['写目标卡', '限定自动任务类型', '建立 PROJECT.md', '创建每日推进 Cron', '每周删减低价值任务'],
          output: '持续更新的 PROJECT.md 和每日推进摘要。',
          kpi: '一周后项目状态更清晰，而不是多出一堆没人处理的提醒。',
        },
        {
          title: '自动化数据报告',
          input: '数据源、指标口径、报告模板、飞书 Webhook、定时频率。',
          steps: ['测试 Webhook', '写需求说明', '生成脚本', '手动运行验数', '接入定时任务'],
          output: '本地脚本可生成报告并推送飞书。',
          kpi: '报告数字与人工核对一致，敏感信息通过环境变量或 Secrets 管理。',
        },
      ],
    },
  ],
};
