import type { ModuleEnhancement } from '@/types/course';

export const llmEnhancement: ModuleEnhancement = {
  lastVerifiedOn: '',
  sources: [],
  blocks: [
    {
      type: 'model-options',
      title: '模型对比与成本估算',
      description: '下面这组数据只用于快速比较，真正接入前仍建议回到官方页面核验。',
      footer: '说明：该估算仅用于快速比较，不包含缓存命中、工具调用、平台加价和区域差异等额外成本。',
      items: [
        {
          name: 'GPT-5.4',
          vendor: 'OpenAI',
          contextWindow: '1.05M',
          inputPerMTok: 2.5,
          outputPerMTok: 15,
          latency: '中',
          bestFor: '复杂专业任务、长链路工作流、需要强工具生态的场景',
          tier: '高质量',
        },
        {
          name: 'GPT-5.4 mini',
          vendor: 'OpenAI',
          contextWindow: '400K',
          inputPerMTok: 0.75,
          outputPerMTok: 4.5,
          latency: '低',
          bestFor: '常规产品功能、轻量多步任务、较高频的日常调用',
          tier: '均衡',
        },
        {
          name: 'GPT-5.4 nano',
          vendor: 'OpenAI',
          contextWindow: '400K',
          inputPerMTok: 0.2,
          outputPerMTok: 1.25,
          latency: '低',
          bestFor: '分类、提取、排序、子代理和高频批量处理',
          tier: '低预算',
        },
        {
          name: 'Claude Opus 4.1',
          vendor: 'Anthropic',
          contextWindow: '200K',
          inputPerMTok: 15,
          outputPerMTok: 75,
          latency: '高',
          bestFor: '高难度推理、复杂代码和高要求长链路分析',
          tier: '高质量',
        },
        {
          name: 'Claude Sonnet 4',
          vendor: 'Anthropic',
          contextWindow: '200K',
          inputPerMTok: 3,
          outputPerMTok: 15,
          latency: '中',
          bestFor: '高质量写作、文档任务、日常工程协作与推理',
          tier: '均衡',
        },
        {
          name: 'DeepSeek V3.2',
          vendor: 'DeepSeek',
          contextWindow: '128K',
          inputPerMTok: 0.28,
          outputPerMTok: 0.42,
          latency: '低',
          bestFor: '低成本高频处理、中文场景探索、批量任务实验',
          tier: '低预算',
        },
      ],
    },
  ],
};
