import type { ModuleEnhancement } from '@/types/course';

export const llmEnhancement: ModuleEnhancement = {
  lastVerifiedOn: '2026-03-31',
  sources: [
    { label: 'OpenAI Pricing', url: 'https://openai.com/api/pricing' },
    { label: 'Anthropic Models', url: 'https://docs.anthropic.com/en/docs/about-claude/models/overview' },
    { label: 'DeepSeek Pricing', url: 'https://api-docs.deepseek.com/quick_start/pricing/' },
    { label: 'Moonshot Kimi', url: 'https://platform.moonshot.cn' },
    { label: 'MiniMax Pricing', url: 'https://platform.minimax.io/docs/guides/pricing-paygo' },
    { label: 'Zhipu GLM Pricing', url: 'https://docs.z.ai/guides/overview/pricing' },
    { label: 'Alibaba Qwen Models', url: 'https://www.alibabacloud.com/help/en/model-studio/models' },
  ],
  blocks: [
    {
      type: 'model-options',
      title: '模型对比与成本估算',
      description: '下面这组数据只用于快速比较，真正接入前请回到官方页面核验。价格和版本可能随时变化。',
      footer: '说明：该估算仅用于快速比较，不包含缓存命中、工具调用、平台加价和区域差异等额外成本。所有价格为美元/百万 token 计价，截至 2026 年 3 月。',
      items: [
        {
          name: 'GPT-5.4',
          vendor: 'OpenAI',
          contextWindow: '1.05M',
          inputPerMTok: 2.5,
          outputPerMTok: 15,
          latency: '中',
          bestFor: '复杂专业任务、长链路工作流、工具生态最完善',
          tier: '高质量',
        },
        {
          name: 'GPT-5.4 mini',
          vendor: 'OpenAI',
          contextWindow: '400K',
          inputPerMTok: 0.75,
          outputPerMTok: 4.5,
          latency: '低',
          bestFor: '日常通用任务、轻量多步推理、高频调用的性价比之选',
          tier: '均衡',
        },
        {
          name: 'GPT-5.4 nano',
          vendor: 'OpenAI',
          contextWindow: '400K',
          inputPerMTok: 0.2,
          outputPerMTok: 1.25,
          latency: '低',
          bestFor: '分类、提取、排序等结构化任务，适合子代理和高频批量处理',
          tier: '低预算',
        },
        {
          name: 'Claude Opus 4.6',
          vendor: 'Anthropic',
          contextWindow: '1M',
          inputPerMTok: 5,
          outputPerMTok: 25,
          latency: '高',
          bestFor: '高难度推理、复杂代码审查、高要求长链路分析',
          tier: '高质量',
        },
        {
          name: 'Claude Sonnet 4.6',
          vendor: 'Anthropic',
          contextWindow: '1M',
          inputPerMTok: 3,
          outputPerMTok: 15,
          latency: '中',
          bestFor: '高质量写作、文档协作、日常工程推理，中文表达自然',
          tier: '均衡',
        },
        {
          name: 'Claude Haiku 4.5',
          vendor: 'Anthropic',
          contextWindow: '1M',
          inputPerMTok: 1,
          outputPerMTok: 5,
          latency: '低',
          bestFor: '分类、提取、高频轻量任务，速度快成本低',
          tier: '低预算',
        },
        {
          name: 'DeepSeek V3.2',
          vendor: 'DeepSeek',
          contextWindow: '128K',
          inputPerMTok: 0.28,
          outputPerMTok: 0.42,
          latency: '低',
          bestFor: '极致低成本、中文场景探索、批量任务实验，开源可自部署',
          tier: '低预算',
        },
        {
          name: 'Kimi K2.5',
          vendor: 'Moonshot',
          contextWindow: '256K',
          inputPerMTok: 0.6,
          outputPerMTok: 3,
          latency: '低',
          bestFor: '多模态理解、代码生成、256K 超长上下文，中文编程场景强',
          tier: '均衡',
        },
        {
          name: 'MiniMax M2.7',
          vendor: 'MiniMax',
          contextWindow: '1M',
          inputPerMTok: 0.3,
          outputPerMTok: 1.2,
          latency: '低',
          bestFor: '自主代理工作流、超长上下文、代码与复杂任务，极致性价比',
          tier: '均衡',
        },
        {
          name: 'GLM-5',
          vendor: 'Zhipu AI',
          contextWindow: '200K',
          inputPerMTok: 1,
          outputPerMTok: 3.2,
          latency: '中',
          bestFor: '复杂系统工程、长链路代理任务、开源 MIT 协议可商用',
          tier: '均衡',
        },
        {
          name: 'Qwen3.5-Plus',
          vendor: 'Alibaba',
          contextWindow: '1M',
          inputPerMTok: 0.4,
          outputPerMTok: 1.2,
          latency: '低',
          bestFor: '中文写作与分析、超长上下文、阿里生态集成，思考模式可用',
          tier: '均衡',
        },
        {
          name: 'Qwen-Max',
          vendor: 'Alibaba',
          contextWindow: '1M',
          inputPerMTok: 1.6,
          outputPerMTok: 6.4,
          latency: '中',
          bestFor: '旗舰级中文推理、高难度分析、需要最强 Qwen 能力的关键任务',
          tier: '高质量',
        },
      ],
    },
  ],
};
