import type { ModuleEnhancement, ModuleId } from '@/types/course';

export const MODULE_ENHANCEMENTS: Record<ModuleId, ModuleEnhancement> = {
  'super-individual': {
    lastVerifiedOn: '2026-03-25',
    sources: [
      { label: 'OpenAI Models Docs', url: 'https://platform.openai.com/docs/models' },
      { label: 'Claude Docs', url: 'https://docs.anthropic.com/' },
      { label: 'DeepSeek API Docs', url: 'https://api-docs.deepseek.com/' },
    ],
    actionChecklist: [
      {
        title: '30 分钟启动任务',
        timebox: '30 分钟',
        description: '用一个固定 Prompt 完成“摘要 + 行动建议 + 下一步”。',
        doneDefinition: '产出 1 份可执行 Markdown 结果并分享到群内/个人知识库。',
      },
      {
        title: '7 天输入法',
        timebox: '每天 20 分钟',
        description: '连续 7 天把重复任务改写成可复用 Prompt 模板。',
        doneDefinition: '至少沉淀 5 个模板（邮件、复盘、计划、分析、脚本）。',
      },
      {
        title: '工具栈最小闭环',
        timebox: '90 分钟',
        description: '对话模型 + 知识库 + 自动化工具跑通一次端到端流程。',
        doneDefinition: '能稳定复现“输入任务 -> 输出结果 -> 自动归档”。',
      },
    ],
  },
  llm: {
    lastVerifiedOn: '2026-03-25',
    sources: [
      { label: 'OpenAI Models', url: 'https://platform.openai.com/docs/models' },
      { label: 'Anthropic Pricing', url: 'https://www.anthropic.com/pricing' },
      { label: 'DeepSeek Pricing', url: 'https://api-docs.deepseek.com/quick_start/pricing' },
      { label: 'Moonshot Docs', url: 'https://platform.moonshot.cn/docs' },
    ],
    modelOptions: [
      {
        name: 'GPT-5.4',
        vendor: 'OpenAI',
        contextWindow: '1M',
        inputPerMTok: 2.5,
        outputPerMTok: 15,
        latency: '中',
        bestFor: '复杂代理、跨工具工作流、高质量代码任务',
        tier: '高质量',
      },
      {
        name: 'GPT-5.4 mini',
        vendor: 'OpenAI',
        contextWindow: '400K',
        inputPerMTok: 0.75,
        outputPerMTok: 4.5,
        latency: '低',
        bestFor: '常规产品功能与日常推理',
        tier: '均衡',
      },
      {
        name: 'Claude Opus 4.6',
        vendor: 'Anthropic',
        contextWindow: '1M',
        inputPerMTok: 5,
        outputPerMTok: 25,
        latency: '高',
        bestFor: '超长上下文与复杂分析',
        tier: '高质量',
      },
      {
        name: 'Claude Sonnet 4.6',
        vendor: 'Anthropic',
        contextWindow: '1M',
        inputPerMTok: 3,
        outputPerMTok: 15,
        latency: '中',
        bestFor: '高质量写作、技术文档、日常开发',
        tier: '均衡',
      },
      {
        name: 'DeepSeek V3.2',
        vendor: 'DeepSeek',
        contextWindow: '128K',
        inputPerMTok: 0.28,
        outputPerMTok: 0.42,
        latency: '低',
        bestFor: '低成本高频任务与批量处理',
        tier: '低预算',
      },
      {
        name: 'Kimi K2.5',
        vendor: 'Moonshot',
        contextWindow: '256K',
        inputPerMTok: 1.2,
        outputPerMTok: 5,
        latency: '中',
        bestFor: '中文多模态与长文本协作',
        tier: '均衡',
      },
    ],
  },
  agents: {
    lastVerifiedOn: '2026-03-29',
    sources: [
      { label: 'OpenClaw', url: 'https://openclaw.ai/' },
      { label: 'OpenClaw GitHub', url: 'https://github.com/openclaw/openclaw' },
      { label: 'Claude Code Changelog', url: 'https://code.claude.com/docs/en/changelog' },
      { label: 'Claude Code Platforms', url: 'https://code.claude.com/docs/en/platforms' },
      { label: 'Claude Code Remote Control', url: 'https://code.claude.com/docs/en/remote-control' },
      { label: 'Claude Code Slack', url: 'https://code.claude.com/docs/en/slack' },
      { label: 'Ollama', url: 'https://ollama.com/' },
    ],
    securityChecklist: [
      { title: '最小权限原则', detail: '默认禁用不必要的系统权限，仅在 Skill 运行时按需开启。' },
      { title: '分离密钥', detail: '开发、测试、生产使用不同 API Key 与配额上限。' },
      { title: '命令白名单', detail: '仅允许有限命令集；高危命令（删除、网络上传）默认禁止。' },
      { title: '文件沙箱目录', detail: '限制到工作目录，避免读取系统敏感路径。' },
      { title: '审计日志', detail: '记录触发时间、执行步骤、外部请求、结果摘要。' },
      { title: '人工确认关卡', detail: '资金、外发消息、批量操作前必须二次确认。' },
      { title: '速率限制', detail: '每小时调用次数与 token 上限，防止误触发烧额度。' },
      { title: '回滚策略', detail: '关键流程先写草稿或影子模式，验证后再正式执行。' },
    ],
  },
  scenarios: {
    lastVerifiedOn: '2026-03-25',
    sources: [
      { label: 'Cursor', url: 'https://cursor.com/' },
      { label: 'OpenAI API', url: 'https://platform.openai.com/docs' },
      { label: 'DeepSeek API', url: 'https://api-docs.deepseek.com/' },
      { label: 'OpenClaw', url: 'https://openclaw.ai/' },
    ],
    sopTemplates: [
      {
        title: '内容创作者 SOP（周更）',
        input: '赛道关键词、目标用户、平台（公众号/抖音/小红书）',
        steps: [
          '抓取 20 条热点并聚类',
          '输出 3 个选题与角度差异',
          '生成脚本初稿并自动审稿',
          '发布后 24 小时抓取数据复盘',
        ],
        output: '1 篇成稿 + 1 条短视频脚本 + 复盘表',
        kpi: '单周产出 >= 2，内容完播/阅读提升 20%',
      },
      {
        title: '独立开发者 SOP（MVP）',
        input: '问题定义、目标用户、核心功能 3 条',
        steps: [
          'Agent 生成技术方案和任务拆分',
          '按优先级实现核心路径',
          '自动生成测试 + 手工验收清单',
          '发布内测并收集反馈',
        ],
        output: '可访问 MVP + issue backlog',
        kpi: '2 周内上线，收集到 >= 10 条真实反馈',
      },
      {
        title: '电商运营 SOP（日频）',
        input: '商品池、客服对话、库存与价格数据',
        steps: [
          '自动分类客服问题并给回复草稿',
          '监控竞品价格变化并推送差异',
          '生成商品图文素材和发布文案',
          '汇总 ROI 和转化漏斗',
        ],
        output: '客服日报 + 竞品差异报告 + 发布素材包',
        kpi: '人工客服时长下降 40%，转化率提升 10%',
      },
    ],
  },
  cases: {
    lastVerifiedOn: '2026-03-25',
    sources: [
      { label: 'TED', url: 'https://www.ted.com/' },
      { label: '腾讯云开发者', url: 'https://cloud.tencent.com/developer' },
      { label: 'Every', url: 'https://every.to/' },
    ],
    caseEvidence: [
      {
        title: 'Ishan Sharma 团队效率案例',
        sourceLabel: 'TED',
        sourceUrl: 'https://www.ted.com/',
        publishedOn: '2025-01-01',
        reproducibility: '中',
        riskWarning: '具备强个人 IP 基础，普通团队直接复制难度较高。',
      },
      {
        title: 'Samuel 转型开发者收入案例',
        sourceLabel: '腾讯云开发者',
        sourceUrl: 'https://cloud.tencent.com/developer',
        publishedOn: '2025-09-01',
        reproducibility: '低',
        riskWarning: '存在样本偏差与知识产权风险，不应按短周期收入做预期。',
      },
      {
        title: 'Every 小团队高营收案例',
        sourceLabel: 'Every',
        sourceUrl: 'https://every.to/',
        publishedOn: '2026-03-01',
        reproducibility: '中',
        riskWarning: '团队具备媒体经验和分发能力，AI 仅是放大器。',
      },
    ],
  },
  growth: {
    lastVerifiedOn: '2026-03-25',
    sources: [
      { label: 'OpenAI Docs', url: 'https://platform.openai.com/docs' },
      { label: 'Claude Docs', url: 'https://docs.anthropic.com/' },
      { label: 'DeepSeek Docs', url: 'https://api-docs.deepseek.com/' },
    ],
    weeklyPlan: [
      { week: 1, goal: '搭建基础工具集', deliverable: '注册并跑通 3 个 AI 工具', fallback: '至少保证 1 个主力模型可稳定使用' },
      { week: 2, goal: '完成 5 个真实任务', deliverable: '沉淀任务-结果对照表', fallback: '保底完成 3 个任务并复盘失败原因' },
      { week: 3, goal: '提炼 Prompt 模板', deliverable: '5 个可复用模板', fallback: '先固化 2 个高频模板' },
      { week: 4, goal: '建立知识库归档', deliverable: '知识库结构 + 标准命名', fallback: '先把本周产出全部归档' },
      { week: 5, goal: '识别可自动化流程', deliverable: '3 条候选工作流', fallback: '先锁定 1 条高频流程' },
      { week: 6, goal: '上线第一条自动化', deliverable: '可定时运行的任务', fallback: '手动半自动流程先跑通' },
      { week: 7, goal: '扩展到多渠道触达', deliverable: '至少 2 个通知渠道', fallback: '先保留一个主通知渠道' },
      { week: 8, goal: '建立质量门禁', deliverable: '发布前检查清单', fallback: '先做人工抽检流程' },
      { week: 9, goal: '试运营 MVP', deliverable: '1 个可展示的产品或服务页', fallback: 'Landing page + 表单先上线' },
      { week: 10, goal: '获取首批反馈', deliverable: '10 条真实反馈', fallback: '至少完成 5 次访谈' },
      { week: 11, goal: '迭代报价与交付', deliverable: '版本化报价单 + 交付模板', fallback: '先完成单一服务报价' },
      { week: 12, goal: '完成首次变现验证', deliverable: '首单或首笔订阅', fallback: '完成 1 次免费试点换案例' },
    ],
  },
};
